export const products = [
    {
        id:1,
        name: 'Hello World!',
        cost: 3,
        baseValue:5,
        mod: 1,
        available: true,
    },
    // {
    //     id:2,
    //     name: 'Calculator',
    //     cost: 30,
    //     baseValue:10,
    //     mod: 1,
    //     available: true,
    // },
    // {
    //     id:3,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:4,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:5,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:6,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:7,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:8,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:9,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // }
]