export const products = [
    //why the fuck did i have modifyer here again??? prob upgrades down the line
    {
        id:1,
        name: 'Hello World!',
        cost: 2.5,
        baseValue:2,
        mod: 1,
        sold: 0,
        
    },
    {
        id:2,
        name: 'Calculator',
        cost: 30,
        baseValue:25,
        mod: 1,
        sold: 0,
        unlock: {money: 30},
    },
    // {
    //     id:3,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:4,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:5,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:6,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:7,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:8,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // },
    // {
    //     id:9,
    //     name: 'Insert',
    //     cost: 0,
    //     baseValue:0,
    //     mod:1,
    //     available: false,
    // }
]